// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Interpreter.Specs.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class РаботаЦикловИУсловийFeature : object, global::Xunit.IClassFixture<РаботаЦикловИУсловийFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("ru-RU"), "Features", "Работа циклов и условий", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Fibonacci.feature"
#line hidden
        
        public РаботаЦикловИУсловийFeature(РаботаЦикловИУсловийFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Fibonacci.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="вычисление n-го числа Фибоначчи итеративным методом")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Работа циклов и условий")]
        [global::Xunit.TraitAttribute("Description", "вычисление n-го числа Фибоначчи итеративным методом")]
        public async global::System.Threading.Tasks.Task ВычислениеN_ГоЧислаФибоначчиИтеративнымМетодом()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("вычисление n-го числа Фибоначчи итеративным методом", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Value"});
                table3.AddRow(new string[] {
                            "7"});
#line 5
       await testRunner.WhenAsync("я ввожу в консоли:", ((string)(null)), table3, "Когда ");
#line hidden
#line 9
        await testRunner.WhenAsync("я выполняю программу:", @"НАЧАЛО
    ЧИСЛО n : ДРОБЬ;
    МОЛВИ(""Введите номер числа Фибоначчи: "");
    ВНЕМЛИ(n);
    
    ЕСЛИ (n == 0) 
    СТАЛОБЫТЬ 
        НАЧАЛО
            ЧИСЛО итеративныйРезультат : ДРОБЬ = 0;
            МОЛВИ(""Итеративно: F("", n, "") = "", итеративныйРезультат);
        ИСХОД
    ИНО
        ЕСЛИ (n == 1) 
        СТАЛОБЫТЬ
            НАЧАЛО
                ЧИСЛО итеративныйРезультат : ДРОБЬ = 1;
                МОЛВИ(""Итеративно: F("", n, "") = "", итеративныйРезультат);
            ИСХОД 
        ИНО
            НАЧАЛО
                ЧИСЛО а : ДРОБЬ = 0;
                ЧИСЛО б : ДРОБЬ = 1;
                ЧИСЛО счетчик : ДРОБЬ = 2;
                
                ПОКУДА (счетчик <= n) 
                ТВОРИ 
                    НАЧАЛО
                        ЧИСЛО временный : ДРОБЬ = а + б;
                        а = б;
                        б = временный;
                        счетчик = счетчик + 1;
                    ИСХОД
                
                МОЛВИ(""Итеративно: F("", n, "") = "", б);
            ИСХОД
        ИСХОД
    ИСХОД
ИСХОД", ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 51
       await testRunner.ThenAsync("я получаю результаты:", "Введите номер числа Фибоначчи: \r\nИтеративно: F(7) = 13", ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await РаботаЦикловИУсловийFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await РаботаЦикловИУсловийFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
