// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Interpreter.Specs.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ПоддержкаРазличныхТиповFeature : object, global::Xunit.IClassFixture<ПоддержкаРазличныхТиповFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("ru-RU"), "Features", "Поддержка различных типов", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "FizzBuzz.feature"
#line hidden
        
        public ПоддержкаРазличныхТиповFeature(ПоддержкаРазличныхТиповFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/FizzBuzz.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Вывод FizzBuzz для первых 15 чисел")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Поддержка различных типов")]
        [global::Xunit.TraitAttribute("Description", "Вывод FizzBuzz для первых 15 чисел")]
        public async global::System.Threading.Tasks.Task ВыводFizzBuzzДляПервых15Чисел()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Вывод FizzBuzz для первых 15 чисел", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Value"});
                table4.AddRow(new string[] {
                            "15"});
#line 5
    await testRunner.WhenAsync("я ввожу в консоли:", ((string)(null)), table4, "Когда ");
#line hidden
#line 9
    await testRunner.WhenAsync("я выполняю программу:", @"НАЧАЛО
    ЧИСЛО n : ДРОБЬ;
    МОЛВИ(""Введите количество чисел для FizzBuzz: "");
    ВНЕМЛИ(n);
    
    ФУНКЦИЯ fizzBuzzДляЧисла(число: ДРОБЬ) : СТРОКА
    НАЧАЛО
        БУЛЕВО делитсяНа3 = (число % 3 == 0);
        БУЛЕВО делитсяНа5 = (число % 5 == 0);
        
        ЕСЛИ (делитсяНа3 @ делитсяНа5) СТАЛОБЫТЬ
        НАЧАЛО
            ДАРОВАТЬ ""FizzBuzz"";
        ИСХОД
        ИНО
        НАЧАЛО
            ЕСЛИ (делитсяНа3) СТАЛОБЫТЬ
            НАЧАЛО
                ДАРОВАТЬ ""Fizz"";
            ИСХОД
            ИНО
            НАЧАЛО
                ЕСЛИ (делитсяНа5) СТАЛОБЫТЬ
                НАЧАЛО
                    ДАРОВАТЬ ""Buzz"";
                ИСХОД
                ИНО
                НАЧАЛО
                    ДАРОВАТЬ числовстроку(число);
                ИСХОД
            ИСХОД
        ИСХОД
    ИСХОД
    
    МОЛВИ(""FizzBuzz от 1 до "", n, "":"");
    ЧИСЛО i : ДРОБЬ = 1;
    
    ПОКУДА (i <= n) ТВОРИ
    НАЧАЛО
        СТРОКА результат = fizzBuzzДляЧисла(i);
        МОЛВИ(результат);
        i = i + 1;
    ИСХОД
ИСХОД", ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 57
    await testRunner.ThenAsync("я получаю результаты:", "Введите количество чисел для FizzBuzz: \r\nFizzBuzz от 1 до 15:\r\n1\r\n2\r\nFizz\r\n4\r\nBuz" +
                        "z\r\nFizz\r\n7\r\n8\r\nFizz\r\nBuzz\r\n11\r\nFizz\r\n13\r\n14\r\nFizzBuzz", ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ПоддержкаРазличныхТиповFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ПоддержкаРазличныхТиповFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
