// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Interpreter.Specs.Features.Semantic
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class РекурсияFeature : object, global::Xunit.IClassFixture<РекурсияFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("ru-RU"), "Features/Semantic", "Рекурсия", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SemanticRecursion.feature"
#line hidden
        
        public РекурсияFeature(РекурсияFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Semantic/SemanticRecursion.feature.ndjson", 6);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Функция вызывает саму себя")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Рекурсия")]
        [global::Xunit.TraitAttribute("Description", "Функция вызывает саму себя")]
        public async global::System.Threading.Tasks.Task ФункцияВызываетСамуСебя()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Функция вызывает саму себя", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
    await testRunner.WhenAsync("я выполняю программу:", "НАЧАЛО\r\n  ФУНКЦИЯ Факториал(n : ДРОБЬ) : ДРОБЬ\r\n  НАЧАЛО\r\n    ЕСЛИ (n <= 1) СТАЛО" +
                        "БЫТЬ\r\n      НАЧАЛО\r\n        ДАРОВАТЬ 1;\r\n      ИСХОД\r\n    ДАРОВАТЬ n * Факториал" +
                        "(n - 1);\r\n  ИСХОД\r\n  МОЛВИ(Факториал(5));\r\nИСХОД", ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 19
    await testRunner.ThenAsync("я получаю результаты:", "120", ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Две функции вызывают друг друга")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Рекурсия")]
        [global::Xunit.TraitAttribute("Description", "Две функции вызывают друг друга")]
        public async global::System.Threading.Tasks.Task ДвеФункцииВызываютДругДруга()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Две функции вызывают друг друга", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
    await testRunner.WhenAsync("я выполняю программу:", @"НАЧАЛО
  ФУНКЦИЯ Четное(n : ДРОБЬ) : БУЛЕВО
  НАЧАЛО
    ЕСЛИ (n == 0) СТАЛОБЫТЬ
      НАЧАЛО
        ДАРОВАТЬ ИСТИНА;
      ИСХОД
    ДАРОВАТЬ Нечетное(n - 1);
  ИСХОД
  ФУНКЦИЯ Нечетное(n : ДРОБЬ) : БУЛЕВО
  НАЧАЛО
    ЕСЛИ (n == 0) СТАЛОБЫТЬ
      НАЧАЛО
        ДАРОВАТЬ ЛОЖЬ;
      ИСХОД
    ДАРОВАТЬ Четное(n - 1);
  ИСХОД
  МОЛВИ(Четное(4));
  МОЛВИ(Четное(5));
ИСХОД", ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 48
    await testRunner.ThenAsync("я получаю результаты:", "ИСТИНА\r\nЛОЖЬ", ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Взаимная рекурсия в одной области видимости")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Рекурсия")]
        [global::Xunit.TraitAttribute("Description", "Взаимная рекурсия в одной области видимости")]
        public async global::System.Threading.Tasks.Task ВзаимнаяРекурсияВОднойОбластиВидимости()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Взаимная рекурсия в одной области видимости", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 55
    await testRunner.WhenAsync("я выполняю программу:", @"НАЧАЛО
ФУНКЦИЯ A(a: ДРОБЬ) : ДРОБЬ
НАЧАЛО
ЕСЛИ(a > 1) СТАЛОБЫТЬ
НАЧАЛО
  ДАРОВАТЬ B(a-1);  
ИСХОД
ДАРОВАТЬ a;
ИСХОД

ФУНКЦИЯ B(b: ДРОБЬ) : ДРОБЬ
НАЧАЛО
ЕСЛИ(b > 1) СТАЛОБЫТЬ
НАЧАЛО
  ДАРОВАТЬ A(b-1);  
ИСХОД
ДАРОВАТЬ b;
ИСХОД

МОЛВИ(A(4));
ИСХОД", ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 79
    await testRunner.ThenAsync("я получаю результаты:", "1", ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Взаимная рекурсия в разных областях видимости")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Рекурсия")]
        [global::Xunit.TraitAttribute("Description", "Взаимная рекурсия в разных областях видимости")]
        public async global::System.Threading.Tasks.Task ВзаимнаяРекурсияВРазныхОбластяхВидимости()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Взаимная рекурсия в разных областях видимости", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 84
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 85
    await testRunner.WhenAsync("я выполняю программу:", "НАЧАЛО\r\n    НАЧАЛО\r\n      ФУНКЦИЯ А() : ДРОБЬ\r\n      НАЧАЛО\r\n        ДАРОВАТЬ 5;\r" +
                        "\n      ИСХОД\r\n    ИСХОД\r\n  ФУНКЦИЯ Б() : ДРОБЬ\r\n  НАЧАЛО\r\n    ДАРОВАТЬ А();\r\n  И" +
                        "СХОД\r\nИСХОД", ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 100
    await testRunner.ThenAsync("я получаю ошибку типа \"UnknownSymbolException\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await РекурсияFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await РекурсияFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
